# Generated by Django 3.2.14 on 2022-08-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bus_name', models.CharField(blank=True, max_length=128)),
                ('bus_type', models.CharField(choices=[('SLEEPER', 'SLEEPER'), ('SEMI_SLEEPER', 'SEMI_SLEEPER'), ('SEATER', 'SEATER')], default='SEATER', max_length=32)),
                ('is_air_conditioned', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('seat_number', models.IntegerField()),
                ('seat_tier', models.CharField(choices=[('LOW', 'LOW'), ('MIDDLE', 'MIDDLE'), ('HIGH', 'HIGH')], default='LOW', max_length=16)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bus.bus')),
            ],
            options={
                'unique_together': {('seat_number', 'bus')},
            },
        ),
    ]
