# Generated by Django 3.2.14 on 2022-08-01 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('pincode', models.CharField(max_length=16, unique=True)),
                ('state', models.CharField(max_length=128)),
                ('country', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='bus.bus')),
                ('origination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='booking_system.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripSeatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('BOOKED', 'BOOKED'), ('AVAILABLE', 'AVAILABLE')], default='AVAILABLE', max_length=32)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.seat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_seat_status', to='booking_system.trip')),
            ],
            options={
                'index_together': {('trip', 'status')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.UUIDField(default=uuid.uuid4)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bus.seat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='booking_system.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'trip', 'seat')},
            },
        ),
    ]
